services:
  review-dash-backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: review-dash-backend

    restart: no

    env_file:
      - .env
    environment:
      PGSSLMODE: disable

    labels:
      - traefik.enable=true

      # Route
      - traefik.http.routers.reviewdash.rule=PathPrefix(`/review-dash`)
      - traefik.http.routers.reviewdash.entrypoints=web

      # Strip prefix
      - traefik.http.middlewares.reviewdash-strip.stripprefix.prefixes=/review-dash
      - traefik.http.routers.reviewdash.middlewares=reviewdash-strip

      # Internal app port
      - traefik.http.services.reviewdash.loadbalancer.server.port=3000

    networks:
      - satyalabs_network

networks:
  satyalabs_network:
    external: true
